### ISSUE TITLE
単語スペル：Perfecture → Prefecture

### ISSUE THREAD

**Issue by kobake** [moonmile/aspnet-mvc-sample#1]
「都道府県」を示すクラスファイル名やクラス名が Perfecture となっているのが気になりました。
正しくは Prefecture であるかと思います。

書籍のほうも同じ表記になっており、同時に直せるのが理想ではあるでしょうが、ご報告まで。

**Comment by moonmile** [comment]
報告をありがとうございます。
痛恨のスペルミスですね。ミススペルを一気に直したときに、間違ったほうに置換してしまった模様です。
書籍のほうは難しいので、コードのほうは VS2017 対応も含めて直したいと思います。

**Comment by moonmile** [comment]
ひと通り、 ミススペルを修正（Prefecture）
vs2017 にアップグレード

**Comment by kobake** [comment]
即時対応ありがとうございます 👍
